// <auto-generated />
using System;
using MeetingManagementWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingManagementWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250411084644_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetingManagementWeb.Models.CorporateCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Corporate_Customer_Tbl");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2ef4b41-a7ef-4f01-985e-a805a2d835cf"),
                            Name = "Generation-Next IT"
                        },
                        new
                        {
                            Id = new Guid("859f0788-3d16-46d3-9421-44802b1e0259"),
                            Name = "XYZ IT"
                        },
                        new
                        {
                            Id = new Guid("0267480b-8765-4347-b5d1-18b8d18358ae"),
                            Name = "FYZ IT"
                        });
                });

            modelBuilder.Entity("MeetingManagementWeb.Models.IndividualCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Individual_Customer_Tbl");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39ea6912-30dd-4626-8426-a8fa39256a2c"),
                            Name = "Abdur Rashed"
                        },
                        new
                        {
                            Id = new Guid("7a5c3041-7e48-40b0-b475-1cdf4bcfafa1"),
                            Name = "Milon Patwary"
                        },
                        new
                        {
                            Id = new Guid("923829fa-54ca-40aa-a0c1-4f121f7a7338"),
                            Name = "Rakib Ahmed"
                        });
                });

            modelBuilder.Entity("MeetingManagementWeb.Models.ProductService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products_Service_Tbl");

                    b.HasData(
                        new
                        {
                            Id = new Guid("050f85ac-aa29-429a-a335-653cd09a196b"),
                            Name = "Consulting",
                            Unit = "Hour"
                        },
                        new
                        {
                            Id = new Guid("ce9466d9-8491-4408-aeeb-a4880d2063e0"),
                            Name = "Software License",
                            Unit = "Piece"
                        },
                        new
                        {
                            Id = new Guid("cd7b345b-3037-4216-8065-9f8d69966ae1"),
                            Name = "Hardware Device",
                            Unit = "Unit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
